version: "3.9"

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # backend:
  #   build: ./fastApi
  #   container_name: fastapi_app
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     DATABASE_URL: postgresql://admin:secret@db:5432/mydb

  frontend:
    build: ./notion.client
    container_name: react_app
    restart: always
    ports:
      - "3000:5002"
    depends_on:
      - backend

volumes:
  postgres_data: